site_name: Fire System Documentation
site_description: 'Documentation for the Redon Tech Fire System'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Redon-Tech-Fire-System'
repo_url: 'https://github.com/Redon-Tech/Redon-Tech-Fire-System'
nav:
    - Home: index.md
    - Setup:
      - Initial Setup: setup/index.md
theme:
  features:
    - navigation.instant
    - navigation.tabs
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: red
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true