site_name: Fire System Documentation
site_description: 'Documentation for the Redon Tech Fire System'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Redon-Tech-Fire-System'
repo_url: 'https://github.com/Redon-Tech/Redon-Tech-Fire-System'
nav:
    - Home: index.md
    - Setup:
      - Initial Setup: setup/index.md
      - Setting Up Buildings: setup/houses.md
      - Settings and Final Setup: setup/settings.md
    - Advanced Usage:
      - API Reference: advanced/api.md

copyright: Copyright &copy; 2024 Redon Tech

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Redon-Tech
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Eb384Xw
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/parker02311

theme:
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.suggest
  name: 'material'
  favicon: assets/favicon.png
  custom_dir: docs/assets/overrides
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: catppuccin-latte
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: catppuccin-mocha
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra_css:
  - assets/css/theme.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - tables
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg